ALTER TABLE agent_gigs ADD COLUMN lifecycle_state TEXT NOT NULL DEFAULT 'POSTED';
ALTER TABLE agent_gigs ADD COLUMN lifecycle_version INTEGER NOT NULL DEFAULT 0;
ALTER TABLE agent_gigs ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

UPDATE agent_gigs
SET lifecycle_state = CASE status
  WHEN 'ACTIVE' THEN 'DISCOVERABLE'
  WHEN 'IN_PROGRESS' THEN 'IN_PROGRESS'
  WHEN 'COMPLETED' THEN 'CLOSED'
  WHEN 'EXPIRED' THEN 'EXPIRED'
  ELSE 'POSTED'
END,
updated_at = COALESCE(created_at, CURRENT_TIMESTAMP);
